name: s159-sphinx
channels:
- conda-forge
- defaults
dependencies:
- ghp-import=0.5.5
- ipython=6.1.0
- jupyter_client=5.1.0
- jupyter_core=4.3.0
- nbconvert=5.3.1
- nbformat=4.4.0
- pandoc=1.19.2.1
- python=3.6.3
- sphinx=1.6.3
- pip:
  - commonmark==0.5.4
  - nbsphinx==0.2.17
  - recommonmark==0.4.0
